ref: new workspace structure and version management (#280)
- [x]  Set `motsu` version to `v0.1.0`
- [x] Improve version management for the workspace
- `contracts`, `lib/crypto`, `examples`, and `benches` use version set
for the whole workspace
- `motsu`, `motsu-proc`, `e2e`, `e2e-proc` have their own version per
crate
- [x] Cleanup dependencies for the workspace
- [x] Add CI checks for pre-publishing on crates.io
- [x] Fix issues with publishing `motsu` to crates.io:
```
cargo publish -p motsu --target wasm32-unknown-unknown --dry-run
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `motsu-proc` does not specify a version
Note: The published dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.
```

---------

(cherry picked from commit b1eef8057c2e438881cd8687d81963452e868c90)